using StackExchange.Redis;

namespace RedisDatabase.Adapters
{
	class StreamConstants
	{
		/// <summary>
		/// The "~" value used with the MAXLEN option.
		/// </summary>
		public static readonly RedisValue ApproximateMaxLen = "~";

		/// <summary>
		/// The "*" value used with the XADD command.
		/// </summary>
		public static readonly RedisValue AutoGeneratedId = "*";

		/// <summary>
		/// The "$" value used in the XGROUP command. Indicates reading only new messages from the stream.
		/// </summary>
		public static readonly RedisValue NewMessages = "$";

		/// <summary>
		/// The "0" value used in the XGROUP command. Indicates reading all messages from the stream.
		/// </summary>
		public static readonly RedisValue AllMessages = "0";

		/// <summary>
		/// The "-" value used in the XRANGE, XREAD, and XREADGROUP commands. Indicates the minimum message ID from the stream.
		/// </summary>
		public static readonly RedisValue ReadMinValue = "-";

		/// <summary>
		/// The "+" value used in the XRANGE, XREAD, and XREADGROUP commands. Indicates the maximum message ID from the stream.
		/// </summary>
		public static readonly RedisValue ReadMaxValue = "+";

		/// <summary>
		/// The ">" value used in the XREADGROUP command. Use this to read messages that have not been delivered to a consumer group.
		/// </summary>
		public static readonly RedisValue UndeliveredMessages = ">";
	}
}
